### ISSUE TITLE
Clicking on the number from the bubble generates a hovering-active state on Pending tab

### ISSUE THREAD

**Issue by Tahhirah** [Vince-F/timelog#11]
1. Go to "All" tab
2. Click on a random number bubble for any of the tasks tabs (or in the right area) of the tabs

- Clicking on the number from the bubble or in the surrounding area, generates a hovering-active state on "Pending" tab
![Clicking on the number from the bubble generates a hovering-active state on Pending tab](https://user-images.githubusercontent.com/50364085/57383287-2f6ae800-71b7-11e9-86f4-ff7cd1f6a72f.png)

**Comment by Vince-F** [comment]
Seems to be implemened intentionally in the component 
https://github.com/angular/components/blob/master/src/material/chips/chip-list.ts#L462

Trying to circumvent that.
